services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=demodb'
      - 'POSTGRES_PASSWORD=12345'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql'
      - './db:/docker-entrypoint-initdb.d:ro'

volumes:
  pgdata:
