spring:
  application:
    name: demo-crud-api
  datasource:
    url: jdbc:postgresql://localhost:5432/demodb
    username: myuser
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org.hibernate.SQL: DEBUG