spring:
  application:
    name: demo-crud-api
  datasource:
    url: jdbc:postgresql://localhost:5432/demodb
    username: myuser
    password: 12345
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  data:
    web:
      pageable:
        default-page-size: 200
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE